apiVersion: v1
kind: Service
metadata:
  name: user-agent
  labels:
    app: user-agent
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31700
    protocol: TCP
  selector:
    app: user-agent
